name: CI

on:
  push:
    branches:
    - action
    tags:
    - '*'

jobs:
  build_and_release:
    name: runimage-openssh
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build archlinux x86_64 package
        run: |
            docker run --rm -it -v "${{ github.workspace }}:/root" --platform=linux/amd64 archlinux:base-devel /root/build.sh

      - name: Build archlinux aarch64 package
        run: |
            docker run --rm -it -v "${{ github.workspace }}:/root" --platform=linux/arm64 lopsided/archlinux:latest /root/build.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: runimage-openssh*.pkg.tar.zst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
